# Tensors

In [1]:
import torch
import numpy as np

## Initializing a Tensor

#### Directly from data

In [14]:
data = [[1,2], [3,4]]
print(f"data: \n {data} \n") 
print(f"data.type: \n {type(data)} \n") # <class 'list'> 
#print(f"data.shape: \n {data.shape} \n") # Error

x_data = torch.tensor(data)
print(f"x_data: \n {x_data} \n")
print(f"x_data.type: \n {type(x_data)} \n") # <class 'torch.Tensor'> 
print(f"x_data.shape: \n {x_data.shape} \n") # torch.Size([2, 2]) 

data: 
 [[1, 2], [3, 4]] 

data.type: 
 <class 'list'> 

x_data: 
 tensor([[1, 2],
        [3, 4]]) 

x_data.type: 
 <class 'torch.Tensor'> 

x_data.shape: 
 torch.Size([2, 2]) 



#### From a NumPy array

In [7]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"np_array: \n {np_array} \n")
print(f"x_np: \n {x_np} \n")

np_array: 
 [[1 2]
 [3 4]] 

x_np: 
 tensor([[1, 2],
        [3, 4]]) 



#### From another tensor:

명시적으로 재정의(Override)하지 않는다면, 인자로 주어진 Tensor의 속성(shape-모양, datatype-자료형)을 유지한다.

In [3]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의  속성을 덮어쓴다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0609, 0.3342],
        [0.6047, 0.9495]]) 



#### With random or constant values:

- shape은 Tensor의 차원(dimension)을 나타내는 튜플(tuple) 형태이다.
- 아래 함수들에서는 출력 텐서의 차원을 결정한다.

In [15]:
shape = (2,3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.8438, 0.3692, 0.2099],
        [0.2872, 0.2071, 0.6097]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Attributes of a Tensor


- Tensor 의 속성은 shape, datatype 및 어느 장치에 저장되는지를 나타낸다.

In [16]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape} ")
print(f"Datatype of tensor: {tensor.dtype} ")
print(f"Device tensor is stored on: {tensor.device} ")

Shape of tensor: torch.Size([3, 4]) 
Datatype of tensor: torch.float32 
Device tensor is stored on: cpu 


## Operations on Tensors

- 전치(transposing, 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등 100가지 이상의 텐선 연산이 가능
- 각 연산들은 (일반적으로 CPU보다 빠른) GPU 에서 실행할 수 있다.
- Colab 을 사용한다면 Edit > Notebook Settings 에서 GPU를 할당할 수 있다.
- 기본적으로 Tensor는 CPU에 생성된다.
- GPU의 가용성(availability)을 확인한 뒤 .to 메소드를 사용하면 GPU로 텐서를 명시적으로 이동할 수 있다.
- 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이 든다.

In [17]:
# GPU가 존재하면 Tensor를 이동한다.
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

몇몇 연산들을 시도 해 본다. NumPy API 에 익숙하다면 Tensor API 를 사용하는 것은 쉽다.

#### Standard numpy-like indexing and slicing:

In [19]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### Joining tensors

- torch.cat 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있다.
- torch.cat 과 미묘하게 다른 또 다른 텐서 결합 연산인 torch.stack 도 참고할 것

In [20]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#### Arithmetic operations

In [25]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산한다.
# y1, y2, y3 는 모두 같은 값을 갖는다.
# tensor.T 는 텐서의 전치(transpose)를 반환한다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# 요소 별 곱(element-wise product)을 계산한다.
# z1, z2, z3는 모두 같은 값을 갖는다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

#### Single-element tensors

- 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, item()을 사용하여 Python 숫자값으로 변환할 수 있다.

In [26]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


#### In-place operations

- 연산 결과를 피연산자(operand) 에 저장하는 연산을 바꿔치기 연산이라고 한다.
- _ 접미사를 갖는다.
- 예를 들어, x_copy_(y) 나 x.t_() 는 x f를 변경한다.
- 바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivate) 계산에 문제가 발생할 수 있다. 따라서 사용을 권장하지 않는다.

In [27]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with NumPy

- CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에 하나를 변경하면 다른 하나도 변경된다.

#### Tensor to NumPy array

In [28]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경 사항이 NumPy 배열에 반영된다.

In [29]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


#### NumPy array to Tensor

In [30]:
n = np.ones(5)
t = torch.from_numpy(n)

In [31]:
np.add(n,1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
